import test from 'node:test';import assert from 'node:assert/strict';
import {readCsv,csvNumber,canonicalListingUrl} from '../src/lib/estate-csv.ts';
import {marketDistribution,refinance,saleProceeds} from '../src/lib/estate-market.ts';
import {opportunityScore} from '../src/lib/estate-opportunity-score.ts';

const scoringBase={title:'Activo',municipality:'Castalla',property_type:'apartment',features:{costsReviewed:true}};
const scoringInputs={purchasePrice:50000,monthlyRent:600,builtAreaM2:70,ltvPct:0,purchaseTaxPct:10,notaryRegistry:1000,appraisal:0,financingFees:0,renovation:0,furniture:0,reserve:0,communityMonthly:0,ibiAnnual:0,insuranceAnnual:0,maintenanceMonthly:0,managementPct:0,vacancyPct:5,otherMonthly:0};
test('CSV preserves quoted delimiters, newlines, escaped quotes and null numbers',()=>{assert.deepEqual(readCsv('title,price\n"Local, centro",85000.50'),[{title:'Local, centro',price:'85000.50'}]);assert.equal(readCsv('a,b\n"one\ntwo","x""y"')[0].a,'one\ntwo');assert.equal(csvNumber('85000.50'),85000.5);assert.equal(csvNumber('85.000,50'),85000.5);assert.equal(csvNumber(''),null);});
test('CSV rejects malformed rows and unsafe headers',()=>{for(const s of ['a,b\n1','a,b\n"broken,2','a,a\n1,2','__proto__,price\na,1'])assert.throws(()=>readCsv(s));});
test('URL canonicalization keeps listing identity query, removes tracking and rejects script',()=>{assert.equal(canonicalListingUrl('https://example.com/?id=2&utm_source=a#x'),'https://example.com/?id=2');assert.throws(()=>canonicalListingUrl('javascript:alert(1)'));});
test('market requires sufficient independent recent evidence',()=>{const now=new Date('2026-10-01');const sample=(i)=>({price:600+i*50,area_m2:80,observed_at:'2026-09-01',similarity:null,url:`https://source.test/${i}`});assert.equal(marketDistribution([sample(1),sample(2)],now).p50,null);const r=marketDistribution([sample(0),sample(1),sample(2),sample(3)],now);assert.equal(r.p50,675);assert.equal(r.n,4);assert.equal(marketDistribution([sample(1),sample(1),sample(2)],now).p50,null);assert.equal(marketDistribution([{...sample(1),observed_at:'2020-01-01'}],now).n,0);});
test('blocking risk cannot be offset by good finance',()=>{const d={...scoringBase,estate_deal_analyses:[{inputs:{...scoringInputs,marketValueEstimate:80000},outputs:{score:100},data_confidence:1}],estate_risks:[{category:'legal',severity:100,confidence:1,is_kill_switch:true,resolved_at:null}]};const s=opportunityScore(d);assert.equal(s.blocked,true);assert.equal(s.score,0);assert.equal(s.rankScore,0);});
test('old condition is independent from investment score',()=>{const d={...scoringBase,estate_deal_analyses:[{inputs:{...scoringInputs,marketValueEstimate:80000},outputs:{score:80},data_confidence:.8}]};assert.equal(opportunityScore({...d,condition:'new'}).score,opportunityScore({...d,condition:'dated'}).score);});
test('unknown dimensions reduce ranking coverage',()=>{const d={property_type:'apartment',features:{},estate_deal_analyses:[{inputs:{purchasePrice:50000},outputs:{score:100},data_confidence:.5}]};const s=opportunityScore(d);assert.equal(s.score,null);assert.equal(s.rankScore,0);assert.ok(s.coverage<50);});
test('exit proceeds preserve negative equity',()=>{assert.equal(refinance(100000,60,70000,2000),-12000);assert.equal(saleProceeds(100000,70000,5000,3000,1000),21000);});
