"use client";
import { useState } from 'react';
import { xirr,forecastError } from '@/lib/estate-performance';
import type { SavedDeal } from '@/lib/estate-store';
import { SectionHead, Panel, Metric, fmtMoney, fmtPct, dealOutput } from './estate-primitives';
export function PortfolioView({deals,onOpen,onOpportunities}:{deals:SavedDeal[];onOpen:(d:SavedDeal)=>void;onOpportunities:()=>void}){
 const assets=deals.filter(d=>['purchased','rehab','marketing','managed'].includes(d.stage));
 const periods=[...new Set(assets.flatMap(d=>(d.estate_actual_performance??[]).map(r=>r.period)))].sort().reverse();
 const [selected,setSelected]=useState('');const period=selected||periods[0]||'';
 const rows=assets.map(deal=>({deal,actual:deal.estate_actual_performance?.find(r=>r.period===period)}));
 const covered=rows.filter(r=>r.actual),total=(key:'valuation'|'debt_balance')=>covered.length===assets.length&&covered.every(r=>r.actual![key]!==null)?covered.reduce((s,r)=>s+r.actual![key]!,0):null;
 const value=assets.length?total('valuation'):null,debt=assets.length?total('debt_balance'):null;
 const noi=covered.length?covered.reduce((s,r)=>s+r.actual!.rent_received-r.actual!.operating_expenses,0):null;
 const days=period?new Date(Number(period.slice(0,4)),Number(period.slice(5,7)),0).getDate():0;
 const occupied=assets.length>0&&days&&covered.length===assets.length&&covered.every(r=>r.actual!.occupied_days!==null)?covered.reduce((s,r)=>s+r.actual!.occupied_days!,0)/(days*assets.length)*100:null;
 const ledger=deals.filter(d=>['purchased','rehab','marketing','managed','sold'].includes(d.stage)).flatMap(d=>(d.estate_investor_cashflows??[]).map(f=>({date:f.occurred_at,amount:f.direction==='contribution'?-f.amount:f.amount})));
 const irr=xirr(ledger);
 const [groupBy,setGroupBy]=useState<'city'|'asset'|'strategy'>('city');
 const calibration=new Map<string,{n:number;error:number}>();
 for(const d of deals)for(const actual of d.estate_actual_performance??[]){const forecast=actual.forecast?.outputs as {netMonthlyCashFlow?:number}|undefined;const error=forecastError(forecast?.netMonthlyCashFlow,actual.rent_received-actual.operating_expenses-actual.debt_payment);if(!error)continue;const key=groupBy==='city'?d.municipality??'Sin municipio':groupBy==='asset'?d.property_type:d.features?.rentalStrategy??'Sin estrategia';const old=calibration.get(key)??{n:0,error:0};calibration.set(key,{n:old.n+1,error:old.error+error.absolute});}
 const timeline=periods.slice().reverse().map(p=>{const records=assets.flatMap(d=>d.estate_actual_performance??[]).filter(r=>r.period===p);return {period:p,n:records.length,cf:records.reduce((s,r)=>s+r.rent_received-r.operating_expenses-r.debt_payment-r.capex,0)};});
 const cf=covered.length?covered.reduce((s,r)=>s+r.actual!.rent_received-r.actual!.operating_expenses-r.actual!.debt_payment-r.actual!.capex,0):null;
 return <div className="view"><SectionHead eyebrow="06 / MEDIR" title="Cartera" action={periods.length?<label>Periodo <select value={period} onChange={e=>setSelected(e.target.value)}>{periods.map(p=><option key={p}>{p}</option>)}</select></label>:undefined}/>
 {!assets.length?<Panel className="onboarding-compact"><div><h2>Todavía no hay activos comprados</h2><p>La cartera se activa al registrar una compra en Pipeline.</p><button className="primary-button" onClick={onOpportunities}>Abrir Pipeline</button></div></Panel>:<>
 <div className="portfolio-kpis"><Metric label="Valor documentado" value={fmtMoney(value)}/><Metric label="Deuda actual" value={fmtMoney(debt)}/><Metric label="Equity" value={fmtMoney(value===null||debt===null?null:value-debt)}/><Metric label="LTV" value={fmtPct(value&&debt!==null?debt/value*100:null)}/><Metric label="Cash-flow real registrado" value={fmtMoney(cf)} note={`${covered.length}/${assets.length} activos · ${period||'sin cierres'}`}/></div>
 <div className="portfolio-kpis"><Metric label="NOI registrado / mes" value={fmtMoney(noi)}/><Metric label="Ocupación documentada" value={fmtPct(occupied)}/><Metric label="XIRR de flujos inversor" value={fmtPct(irr===null?null:irr*100)} note="ACT/365 · aportaciones/distribuciones; excluye equity retenido"/><Metric label="Retorno cash / equity del mes" value={fmtPct(cf!==null&&value!==null&&debt!==null&&value>debt?cf/(value-debt)*100:null)}/></div>
 <Panel><h2>Previsión frente a realidad</h2><p>Importes mensuales. Sin cierre registrado se muestra «Sin datos».</p><div className="portfolio-table"><div className="portfolio-table-row"><b>Activo</b><b>Previsto</b><b>Real</b><b>Desviación</b><b>CAPEX</b></div>{rows.map(({deal,actual})=>{const forecast=actual?.forecast?.outputs as {netMonthlyCashFlow?:number}|undefined;const predicted=forecast?.netMonthlyCashFlow??dealOutput(deal)?.netMonthlyCashFlow;const real=actual?actual.rent_received-actual.operating_expenses-actual.debt_payment-actual.capex:null;return <button className="portfolio-table-row" key={deal.id} onClick={()=>onOpen(deal)}><strong>{deal.title}<small>{deal.municipality}</small></strong><span>{fmtMoney(predicted)}</span><span>{real===null?'Sin datos':fmtMoney(real)}</span><span>{real===null||predicted===undefined?'—':fmtMoney(real-predicted)}</span><span>{fmtMoney(actual?.capex)}</span></button>;})}</div></Panel><Panel><h2>Evolución de cash-flow registrado</h2>{timeline.map(t=><div className="attention-row" key={t.period}><span>{t.period} · {t.n}/{assets.length} activos</span><strong>{fmtMoney(t.cf)}</strong></div>)}</Panel>
 <Panel><h2>Error de previsión · revisión del modelo</h2><label>Agrupar por<select value={groupBy} onChange={e=>setGroupBy(e.target.value as typeof groupBy)}><option value="city">Municipio</option><option value="asset">Tipo de activo</option><option value="strategy">Estrategia</option></select></label><p>Cash-flow mensual antes de CAPEX extraordinario frente a la previsión guardada. No modifica modelos automáticamente. Meses del mismo activo no son observaciones independientes.</p>{[...calibration].map(([group,g])=><div className="attention-row" key={group}><strong>{group}</strong><span>N {g.n} cierres · error medio {fmtMoney(g.error/g.n)}/mes</span></div>)}</Panel></>}
 </div>;
}
