"use client";
import {useState,type FormEvent} from 'react';
import type {User} from '@supabase/supabase-js';
import {saveRenovationItem,deleteRenovationItem,type SavedDeal} from '@/lib/estate-store';
import {Panel,fmtMoney,dealInput} from './estate-primitives';
export function RenovationDesk({user,deal,run}:{user:User;deal:SavedDeal;run:(task:()=>Promise<void>)=>Promise<void>}){
 const items=deal.estate_renovation_items??[],input=dealInput(deal);
 const [mode,setMode]=useState<'pro'|'diy'|'hybrid'>('pro'),[quantity,setQuantity]=useState(1),[unit,setUnit]=useState(0),[materials,setMaterials]=useState(0),[labor,setLabor]=useState(0),[contingency,setContingency]=useState(10);
 const cost=(quantity*unit+materials+labor)*(1+contingency/100);
 const itemCost=(item:typeof items[number])=>item.mode==='pro'?item.pro_cost:item.mode==='diy'?item.diy_material_cost:item.hybrid_cost;
 const total=items.reduce((s,i)=>s+itemCost(i),0);
 const marketRoom=input?.marketValueEstimate?Math.max(0,input.marketValueEstimate-input.purchasePrice-input.purchasePrice*input.purchaseTaxPct/100-input.notaryRegistry-input.appraisal-input.financingFees-input.furniture):null;
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);await run(async()=>{await saveRenovationItem(user,deal.id,{category:String(data.get('category')),description:String(data.get('description')??''),mode,quantity,unit_cost:unit,materials,labor,contingency_pct:contingency,pro_cost:mode==='pro'?cost:0,diy_material_cost:mode==='diy'?cost:0,hybrid_cost:mode==='hybrid'?cost:0,diy_hours:Number(data.get('hours')),professional_required:data.get('professional')==='on',supplier_quote_url:String(data.get('quote')||'')||null,estimated_rent_uplift_monthly:Number(data.get('rent')),estimated_value_uplift:Number(data.get('value')),risk_reduction:Number(data.get('risk')),confidence:Number(data.get('confidence'))});form.reset();});}
 return <div className="operations-grid"><Panel><h2>Presupuesto de reforma</h2><p>Total de partidas: <strong>{fmtMoney(total)}</strong> · provisión del análisis: {fmtMoney(input?.renovation)}.</p><p>Margen hasta valor de mercado estimado: {fmtMoney(marketRoom)}. Es un techo orientativo antes de beneficio; depende de una valoración válida, no un presupuesto recomendado.</p>{marketRoom!==null&&total>marketRoom&&<p role="status">La reforma supera el margen disponible hasta el valor estimado.</p>}
 <div className="comparison-table"><table><caption>Matriz de retorno de reforma · todas las mejoras son estimaciones</caption><thead><tr><th>Partida</th><th>Coste</th><th>Renta / mes</th><th>Valor</th><th>Riesgo reducido</th><th>Recuperación por renta</th><th>Fuente</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><th>{i.category}<small>{i.mode.toUpperCase()} · {Math.round(i.confidence*100)}%</small></th><td>{fmtMoney(itemCost(i))}</td><td>{fmtMoney(i.estimated_rent_uplift_monthly)}</td><td>{fmtMoney(i.estimated_value_uplift)}</td><td>{i.risk_reduction??'Sin evaluar'}</td><td>{i.estimated_rent_uplift_monthly>0?`${Math.ceil(itemCost(i)/i.estimated_rent_uplift_monthly)} meses`:'Sin retorno estimado'}</td><td>{i.supplier_quote_url?<a href={i.supplier_quote_url} target="_blank" rel="noreferrer">Presupuesto</a>:'Sin presupuesto'}<button aria-label={`Eliminar ${i.category}`} onClick={()=>run(()=>deleteRenovationItem(user,i.id))}>Eliminar</button></td></tr>)}</tbody></table></div></Panel>
 <Panel><h3>Añadir partida</h3><form className="operation-form" onSubmit={submit}><label>Categoría<select name="category">{['Cocina','Baños','Electricidad','Fontanería','Pintura','Suelo','Ventanas','Climatización','Aislamiento','Carpintería','Mobiliario','Otros'].map(c=><option key={c}>{c}</option>)}</select></label><label>Descripción<textarea name="description"/></label><label>Ejecución<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="pro">Profesional</option><option value="diy">DIY</option><option value="hybrid">Híbrido</option></select></label>{([['Cantidad',quantity,setQuantity],['Precio unitario €',unit,setUnit],['Materiales adicionales €',materials,setMaterials],['Mano de obra adicional €',labor,setLabor],['Contingencia %',contingency,setContingency]] as const).map(([label,value,set])=><label key={label}>{label}<input type="number" min={label==='Cantidad'?0.01:0} max={label==='Contingencia %'?100:undefined} step="any" required value={value} onChange={e=>set(Number(e.target.value))}/></label>)}<p>No cuentes dos veces materiales/mano de obra ya incluidos en el precio unitario. Total: {fmtMoney(cost)}.</p><label>Horas DIY<input name="hours" type="number" min="0" defaultValue={0}/></label><label>Renta adicional estimada €/mes<input name="rent" type="number" min="0" defaultValue={0}/></label><label>Valor adicional estimado €<input name="value" type="number" min="0" defaultValue={0}/></label><label>Reducción de riesgo estimada 0–100<input name="risk" type="number" min="0" max="100" defaultValue={0}/></label><label>Confianza 0–1<input name="confidence" type="number" min="0" max="1" step=".1" defaultValue={.5}/></label><label>URL presupuesto proveedor<input name="quote" type="url"/></label><label><input name="professional" type="checkbox"/> Profesional obligatorio</label><button className="primary-button" disabled={cost<=0}>Guardar partida</button></form></Panel></div>;
}
