"use client";
import { useEffect, useState, type FormEvent } from 'react';
import type { User } from '@supabase/supabase-js';
import type { SavedDeal } from '@/lib/estate-store';
import { loadOperations, saveOperation, type OperationTable, type OperationalRecord } from '@/lib/estate-operations';
import { dealInput, dealOutput, fmtMoney, Panel } from './estate-primitives';
import { supabase } from '@/lib/supabase';
import { mortgagePayment } from '@/lib/estate-engine';
import { marketDistribution, refinance, saleProceeds } from '@/lib/estate-market';

type Field = {key:string;label:string;type?:string;options?:string[];optional?:boolean};
const sections:Record<string,{table:OperationTable;label:string;fields:Field[]}>= {
 tasks:{table:'estate_tasks',label:'Plan y tareas',fields:[{key:'title',label:'Siguiente acción'},{key:'due_at',label:'Fecha límite',type:'datetime-local',optional:true},{key:'owner_label',label:'Responsable',optional:true}]},
 visits:{table:'estate_visits',label:'Visitas',fields:[{key:'scheduled_at',label:'Fecha de visita',type:'datetime-local'},{key:'notes',label:'Notas y medidas',type:'textarea',optional:true}]},
 offers:{table:'estate_offers',label:'Negociación',fields:[{key:'amount',label:'Importe €',type:'number'},{key:'direction',label:'Tipo',options:['offer','counteroffer']},{key:'conditions',label:'Condiciones',type:'textarea',optional:true},{key:'expires_at',label:'Caducidad',type:'datetime-local',optional:true}]},
 documents:{table:'estate_documents',label:'Documentos',fields:[{key:'title',label:'Documento'},{key:'category',label:'Categoría',options:['nota_simple','catastro','comunidad','ITE_IEE','urbanismo','licencia','seguro','fiscalidad','other']},{key:'url',label:'Enlace privado al documento',type:'url'}]},
 actual:{table:'estate_actual_performance',label:'Resultado real',fields:[{key:'period',label:'Mes (primer día)',type:'date'},{key:'rent_received',label:'Renta cobrada €',type:'number'},{key:'operating_expenses',label:'Gastos operativos €',type:'number'},{key:'debt_payment',label:'Cuota de deuda €',type:'number'},{key:'capex',label:'CAPEX / reforma €',type:'number'},{key:'debt_balance',label:'Saldo de deuda €',type:'number',optional:true},{key:'valuation',label:'Tasación / valor documentado €',type:'number',optional:true},{key:'occupied_days',label:'Días ocupado',type:'number',optional:true},{key:'source',label:'Fuente / justificante'}]},
 tenants:{table:'estate_tenancies',label:'Explotación y alquiler',fields:[{key:'stage',label:'Fase',options:['ready','marketing','leads','visits','screening','contract','occupied','ended']},{key:'asking_rent',label:'Renta anunciada €',type:'number',optional:true},{key:'achieved_rent',label:'Renta acordada €',type:'number',optional:true},{key:'started_at',label:'Inicio',type:'date',optional:true},{key:'ended_at',label:'Fin',type:'date',optional:true},{key:'channel',label:'Canal',optional:true},{key:'channel_cost',label:'Coste del canal €',type:'number',optional:true},{key:'leads',label:'Contactos',type:'number',optional:true},{key:'visits',label:'Visitas',type:'number',optional:true}]},
 comps:{table:'estate_comparables',label:'Comparables',fields:[{key:'municipality',label:'Municipio'},{key:'property_type',label:'Tipo',options:['apartment','house','studio','commercial','office','building','garage','land']},{key:'transaction_type',label:'Operación',options:['rent','sale']},{key:'price',label:'Precio €',type:'number'},{key:'area_m2',label:'Superficie m²',type:'number'},{key:'source',label:'Fuente'},{key:'url',label:'URL',type:'url'},{key:'observed_at',label:'Fecha observada',type:'date'},{key:'similarity',label:'Similitud 0–1 (si evaluada)',type:'number',optional:true}]},
 evidence:{table:'estate_evidence',label:'Evidencias',fields:[{key:'field',label:'Dato evaluado'},{key:'kind',label:'Tipo',options:['fact','estimate','assumption']},{key:'value',label:'Valor / rango'},{key:'source',label:'Fuente'},{key:'url',label:'URL',type:'url',optional:true},{key:'observed_at',label:'Fecha',type:'datetime-local'},{key:'method',label:'Método / modelo'},{key:'confidence',label:'Confianza 0–1',type:'number'}]},
};
const checklist=['Electricidad','Presión de agua','Humedades visibles','Ventanas','Ruido','Luz y orientación','Estructura visual','Cubierta y fachada','Ascensor','Zonas comunes','Ocupación','Suministros','Medidas','Licencia y uso','Salida de emergencia','Ventilación'];
const translations:Record<string,string>={open:'Pendiente',done:'Hecha',offer:'Oferta',counteroffer:'Contraoferta',ready:'Preparado',marketing:'Anunciado',leads:'Contactos',visits:'Visitas',screening:'Evaluación económica',contract:'Contrato',occupied:'Ocupado',ended:'Finalizado',rent:'Alquiler',sale:'Venta',fact:'Hecho',estimate:'Estimación',assumption:'Supuesto'};
export function OperationsDesk({user,deal,onRefresh}:{user:User;deal:SavedDeal;onRefresh:()=>Promise<void>}){
 const [section,setSection]=useState('tasks'),[rows,setRows]=useState<Partial<Record<OperationTable,OperationalRecord[]>>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 const [checks,setChecks]=useState<Record<string,string>>({});
 useEffect(()=>{let active=true;loadOperations(deal.id).then(data=>{if(active)setRows(data);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[deal.id,revision]);
 const config=sections[section], records=rows[config.table] ?? [];
 const acquired=['purchased','rehab','marketing','managed','sold'].includes(deal.stage);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;setBusy(true);setMessage('');
 try{const fd=new FormData(form),values:Record<string,unknown>={};
 for(const field of config.fields){const raw=String(fd.get(field.key)??'').trim(); values[field.key]=!raw?null:field.type==='number'?Number(raw):field.type==='datetime-local'?new Date(raw).toISOString():raw;}
 if(section==='tasks')values.status='open';
 if(section==='visits'){values.checklist=checks;values.completed_at=fd.get('completed')?new Date().toISOString():null;}
 if(section==='actual'){if(!acquired)throw new Error('Solo activos comprados admiten resultados reales.');if(String(values.period).slice(-2)!=='01')throw new Error('Selecciona el primer día del mes.');values.forecast={engine:dealOutput(deal)?.engineVersion,inputs:dealInput(deal),outputs:dealOutput(deal)};}
 if(section==='comps' && Number(values.similarity)>1)throw new Error('Similitud debe estar entre 0 y 1.');
 await saveOperation(config.table,user.id,deal.id,values);await onRefresh();form.reset();setChecks({});setRevision(r=>r+1);setMessage('Guardado y confirmado por la base de datos.');
 }catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function complete(row:OperationalRecord){try{await saveOperation('estate_tasks',user.id,deal.id,{status:row.status==='done'?'open':'done'},row.id);setRevision(r=>r+1);}catch(e){setMessage(String(e));}}
 const comps=(rows.estate_comparables??[]).filter(r=>r.transaction_type==='rent' && r.property_type===deal.property_type && r.municipality===deal.municipality).map(r=>({price:Number(r.price),area_m2:Number(r.area_m2),observed_at:String(r.observed_at),similarity:r.similarity===null?null:Number(r.similarity),url:String(r.url)}));
 const dist=marketDistribution(comps);
 return <div className="operations-desk"><nav className="operation-nav" aria-label="Operativa del inmueble">{Object.entries(sections).map(([key,s])=><button className={key===section?'active':''} key={key} onClick={()=>setSection(key)}>{s.label}<span>{rows[s.table]?.length ?? '—'}</span></button>)}</nav>
 <div className="operations-body"><h2>{config.label}</h2>{message&&<p role="status">{message}</p>}
 {section==='comps'&&<div className="metric-strip"><span>N {dist.n} · {dist.status==='insufficient'?'Muestra insuficiente':dist.status==='indicative'?'Orientativa':'Útil'} · últimos 180 días</span><strong>P25 {fmtMoney(dist.p25)} · P50 {fmtMoney(dist.p50)} · P75 {fmtMoney(dist.p75)}</strong></div>}
 {section==='offers'&&<div className="metric-strip">Pedido {fmtMoney(dealInput(deal)?.purchasePrice)} · Mercado {fmtMoney(dealInput(deal)?.marketValueEstimate)} · Máximo {fmtMoney(dealOutput(deal)?.maxPurchasePrice)} · Apertura (supuesto −5%) {fmtMoney(dealOutput(deal)?.recommendedOpeningOffer)}</div>}
 <div className="operations-grid"><Panel><form key={section} className="operation-form" onSubmit={submit}>
 {config.fields.map(field=><label key={field.key}>{field.label}{field.optional?' · opcional':''}{field.options?<select name={field.key} defaultValue={field.key==='property_type'?deal.property_type:field.options[0]}>{field.options.map(value=><option key={value} value={value}>{translations[value]??value}</option>)}</select>:field.type==='textarea'?<textarea name={field.key} required={!field.optional}/>:<input name={field.key} type={field.type??'text'} step="any" min={field.type==='number'?0:undefined} required={!field.optional} defaultValue={field.key==='municipality'?deal.municipality??'':undefined}/>}</label>)}
 {section==='visits'&&<fieldset><legend>Comprobaciones en visita</legend>{checklist.map(label=><label key={label}>{label}<select value={checks[label]??'pending'} onChange={e=>setChecks({...checks,[label]:e.target.value})}><option value="pending">Sin comprobar</option><option value="verified">Comprobado</option><option value="needs_inspection">Requiere inspección / riesgo</option><option value="not_applicable">No aplica</option></select></label>)}<label><input type="checkbox" name="completed"/> Visita finalizada</label><p>Al finalizar se registran riesgos bloqueantes para los hallazgos que requieren inspección y una tarea de seguimiento. Incorpora los presupuestos al reanalizar: no se inventarán costes.</p></fieldset>}
 <button className="primary-button" disabled={busy || (section==='actual'&&!acquired)}>{busy?'Guardando…':'Guardar registro'}</button></form></Panel>
 <Panel><h3>Historial</h3>{!records.length?<p>Sin registros. Los datos aparecerán después de guardarlos.</p>:records.map(row=><article className="operation-record" key={row.id}><small>{new Date(row.created_at).toLocaleString('es-ES')}</small>{config.fields.map(field=><div key={field.key}><span>{field.label}</span><strong>{row[field.key]===null?'Sin datos':translations[String(row[field.key])]??String(row[field.key]??'—')}</strong></div>)}{section==='tasks'&&<button className="ghost-button" onClick={()=>complete(row)}>{row.status==='done'?'Reabrir':'Marcar hecha'}</button>}{section==='actual'&&<div><span>Cash-flow real del mes</span><strong>{fmtMoney(Number(row.rent_received)-Number(row.operating_expenses)-Number(row.debt_payment)-Number(row.capex))}</strong></div>}</article>)}</Panel></div>
 {section==='actual'&&<StrategyDesk deal={deal} user={user}/>}</div></div>;
}
function StrategyDesk({deal,user}:{deal:SavedDeal;user:User}){
 const input=dealInput(deal),out=dealOutput(deal);const [value,setValue]=useState(input?.marketValueEstimate??0),[debt,setDebt]=useState(out?.loanAmount??0),[ltv,setLtv]=useState(60),[fees,setFees]=useState(0),[taxes,setTaxes]=useState(0),[agency,setAgency]=useState(0),[interest,setInterest]=useState(3.5),[years,setYears]=useState(25),[message,setMessage]=useState('');
 const payment=mortgagePayment(value*ltv/100,interest,years),noi=out?.noiMonthly??null;
 const outputs={released:refinance(value,ltv,debt,fees),saleNet:saleProceeds(value,debt,taxes,agency,fees),postRefinancePayment:payment,postRefinanceCashFlow:noi===null?null:noi-payment,postRefinanceDscr:noi===null||!payment?null:noi/payment,holdMonthly:out?.netMonthlyCashFlow??null};
 async function save(){const {error}=await supabase.from('estate_strategy_snapshots').insert({user_id:user.id,property_id:deal.id,inputs:{value,debt,ltv,fees,taxes,agency,interest,years,noi},outputs,model_version:'estate_strategy_v1'});setMessage(error?error.message:'Escenario guardado con fecha y versión.');}
 return <Panel><h3>Mantener · refinanciar · vender</h3><p>Supuestos editables. La deuda inicial es la del análisis, sustitúyela por el saldo actual. No representa aprobación bancaria.</p><div className="field-grid three">{([['Valor / precio',value,setValue],['Deuda pendiente',debt,setDebt],['LTV %',ltv,setLtv],['Gastos totales',fees,setFees],['Impuestos venta',taxes,setTaxes],['Agencia venta',agency,setAgency],['Interés nuevo %',interest,setInterest],['Plazo nuevo años',years,setYears]] as const).map(([label,v,set])=><label key={label}>{label}<input type="number" min="0" max={label==='LTV %'?100:undefined} value={v} onChange={e=>set(Number(e.target.value))}/></label>)}</div><p>Refinanciar: capital liberado {fmtMoney(outputs.released)} · cuota {fmtMoney(payment)} · cash-flow {fmtMoney(outputs.postRefinanceCashFlow)}/mes · DSCR {outputs.postRefinanceDscr?.toFixed(2)??'Sin datos'}. Vender: neto {fmtMoney(outputs.saleNet)}. Mantener: cash-flow previsto {fmtMoney(outputs.holdMonthly)}/mes.</p><button className="ghost-button" onClick={save}>Guardar escenario de estrategia</button>{message&&<p role="status">{message}</p>}</Panel>;
}
