"use client";
import { useEffect,useState,type ChangeEvent } from 'react';
import { supabase } from '@/lib/supabase';
import { marketDistribution } from '@/lib/estate-market';
import { readCsv,csvNumber,canonicalListingUrl } from '@/lib/estate-csv';
import { Panel,SectionHead,Metric,fmtMoney } from './estate-primitives';
type Comp={id:string;municipality:string;property_type:string;transaction_type:string;price:number;area_m2:number;observed_at:string;similarity:number|null;url:string;source:string};
export function MarketIntelligence(){
 const [rows,setRows]=useState<Comp[]>([]),[city,setCity]=useState(''),[type,setType]=useState('apartment'),[transaction,setTransaction]=useState('rent'),[message,setMessage]=useState(''),[revision,setRevision]=useState(0),[minimum,setMinimum]=useState(3),[authenticated,setAuthenticated]=useState<boolean|null>(null);
 useEffect(()=>{let active=true;(async()=>{const {data:userData}=await supabase.auth.getUser();if(!active)return;if(!userData.user){setAuthenticated(false);setRows([]);setMessage('');return;}setAuthenticated(true);const {data,error}=await supabase.from('estate_comparables').select('*').order('observed_at',{ascending:false}).limit(500);if(!active)return;if(error)setMessage('No se pudo cargar la muestra privada.');else{setMessage('');setRows(data??[]);}})();return()=>{active=false;};},[revision]);
 const filtered=rows.filter(r=>(!city||r.municipality.toLowerCase().includes(city.toLowerCase()))&&r.property_type===type&&r.transaction_type===transaction);
 const dist=marketDistribution(filtered,new Date(),minimum,Math.max(10,minimum));
 async function importCsv(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;setMessage('');try{
 const {data}=await supabase.auth.getUser();if(!data.user)throw new Error('Inicia sesión para importar comparables.');
 const parsed=readCsv(await file.text());const pending=parsed.map((r,i)=>{
 const price=csvNumber(r.price),area=csvNumber(r.area_m2);if(!r.municipality||!r.property_type||!['rent','sale'].includes(r.transaction_type)||!price||price<=0||!area||area<=0||!r.source||!/^\d{4}-\d{2}-\d{2}$/.test(r.observed_at)||!Number.isFinite(Date.parse(r.observed_at)))throw new Error(`Fila ${i+2}: faltan datos o hay valores inválidos.`);
 return {user_id:data.user!.id,municipality:r.municipality,property_type:r.property_type,transaction_type:r.transaction_type,price,area_m2:area,source:r.source,url:canonicalListingUrl(r.url),observed_at:r.observed_at,similarity:null};});
 const unique=[...new Map(pending.map(r=>[`${r.url}|${r.observed_at}`,r])).values()];const {error}=await supabase.from('estate_comparables').upsert(unique,{onConflict:'user_id,url,observed_at'});if(error)throw error;setRevision(x=>x+1);setMessage(`${unique.length} comparables guardados; los duplicados se actualizan.`);
 }catch(error){setMessage(error instanceof Error?error.message:'Error de importación.');}finally{e.target.value='';}}
 const max=Math.max(1,...filtered.map(r=>r.price/r.area_m2));
 return <div className="view"><SectionHead eyebrow="03 / CONTRASTAR" title="Mercado con evidencia" action={authenticated?<label className="upload-button">Importar comparables CSV<input type="file" accept=".csv" onChange={importCsv}/></label>:null}/>
 <div className="market-controls"><label>Municipio<input value={city} onChange={e=>setCity(e.target.value)} placeholder="Filtrar municipio"/></label><label>Activo<select value={type} onChange={e=>setType(e.target.value)}>{['apartment','house','studio','commercial','office','building','garage','land'].map(t=><option key={t}>{t}</option>)}</select></label><label>Operación<select value={transaction} onChange={e=>setTransaction(e.target.value)}><option value="rent">Alquiler</option><option value="sale">Venta</option></select></label><label>Muestra mínima<input type="number" min="3" max="100" value={minimum} onChange={e=>setMinimum(Math.max(3,Number(e.target.value)))}/></label></div>
 {authenticated===false&&<p className="market-auth-note" role="status">Inicia sesión para consultar tu muestra privada.</p>}{message&&<p role="status">{message}</p>}<div className="portfolio-kpis"><Metric label="N recientes y únicos" value={dist.n}/><Metric label="P25" value={fmtMoney(dist.p25)}/><Metric label="P50" value={fmtMoney(dist.p50)}/><Metric label="P75" value={fmtMoney(dist.p75)}/><Metric label="Calidad de muestra" value={dist.status==='insufficient'?'Insuficiente':dist.status==='indicative'?'Orientativa':'Útil'} note="180 días · anuncios, no transacciones cerradas"/></div>
 <Panel><h2>Comparables externos</h2><p>Las operaciones propias no son testigos de mercado. Filtra una tipología y una zona comparable antes de interpretar el rango.</p>{!filtered.length?<p>{authenticated===false?'Sin sesión no se cargan comparables privados.':'Sin comparables. Importa datos de fuentes autorizadas o añádelos en el inmueble.'}</p>:<><svg className="comparable-chart" viewBox="0 0 800 180" role="img" aria-label="Distribución de precio por metro cuadrado de los comparables"><line x1="20" y1="145" x2="780" y2="145" stroke="currentColor"/>{filtered.slice(0,200).map((r,i)=><circle key={r.id} cx={20+r.price/r.area_m2/max*740} cy={40+(i%5)*20} r="5" fill="var(--accent)"><title>{r.municipality}: {Math.round(r.price/r.area_m2)} €/m² · {r.observed_at}</title></circle>)}</svg><div className="portfolio-table">{filtered.map(r=><a className="portfolio-table-row" key={r.id} href={r.url} target="_blank" rel="noreferrer"><strong>{r.municipality}</strong><span>{fmtMoney(r.price)}</span><span>{r.area_m2} m²</span><span>{fmtMoney(r.price/r.area_m2)}/m²</span><span>{r.observed_at} · {r.source}</span></a>)}</div></>}</Panel>
 <details className="panel"><summary>Formato y fuentes</summary><p>CSV: municipality,property_type,transaction_type,price,area_m2,source,url,observed_at. Fecha AAAA-MM-DD; rent o sale. No se infiere similitud ni distancia.</p><p>idealista/data y CASAFARI requieren contrato e integración validada. Ningún feed comercial está conectado en esta versión.</p></details></div>;
}
