begin;

-- Firekworks Estate V1 core schema.
-- PROPERTY is the physical asset; LISTING is a publication/source for that asset.
-- Every tenant-owned child relation carries user_id in the foreign key to reduce BOLA risk.

create table public.estate_investor_profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  display_name text,
  available_capital numeric(14,2) not null default 0 check (available_capital >= 0),
  monthly_savings numeric(14,2) not null default 0 check (monthly_savings >= 0),
  target_monthly_cashflow numeric(14,2) not null default 250,
  target_net_yield_pct numeric(6,3) not null default 8,
  max_legal_risk smallint not null default 40 check (max_legal_risk between 0 and 100),
  diy_level smallint not null default 70 check (diy_level between 0 and 100),
  preferred_radius_km integer not null default 100 check (preferred_radius_km between 1 and 5000),
  preferred_markets text[] not null default array['Castalla','Onil','Ibi','Villena','Alicante'],
  preferences jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.estate_properties (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  property_type text not null default 'apartment' check (property_type in ('apartment','house','studio','commercial','office','land','building','other')),
  stage text not null default 'analyzing' check (stage in ('watchlist','analyzing','visit','negotiating','discarded','purchased','managed','sold')),
  address text,
  municipality text,
  province text,
  region text,
  country_code char(2) not null default 'ES',
  latitude numeric(9,6),
  longitude numeric(9,6),
  built_area_m2 numeric(10,2) check (built_area_m2 is null or built_area_m2 > 0),
  usable_area_m2 numeric(10,2) check (usable_area_m2 is null or usable_area_m2 > 0),
  bedrooms smallint check (bedrooms is null or bedrooms >= 0),
  bathrooms smallint check (bathrooms is null or bathrooms >= 0),
  floor_label text,
  has_elevator boolean,
  has_terrace boolean,
  has_balcony boolean,
  has_garage boolean,
  has_storage boolean,
  has_pool boolean,
  orientation text,
  year_built smallint check (year_built is null or year_built between 1500 and 2200),
  condition text check (condition is null or condition in ('new','renovated','good','dated','light_renovation','medium_renovation','full_renovation','unknown')),
  energy_rating text,
  occupancy_status text not null default 'vacant' check (occupancy_status in ('vacant','tenant','owner','occupied_unknown','illegal_occupation','usufruct','bare_ownership','unknown')),
  features jsonb not null default '{}'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id)
);

create index estate_properties_user_stage_idx on public.estate_properties(user_id, stage, updated_at desc);
create index estate_properties_market_idx on public.estate_properties(user_id, municipality, property_type);

create table public.estate_listings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  portal text not null default 'manual',
  external_id text,
  url text,
  asking_price numeric(14,2) not null check (asking_price > 0),
  description text,
  agency_name text,
  seller_type text check (seller_type is null or seller_type in ('private','agency','bank','servicer','auction','other')),
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  raw_data jsonb not null default '{}'::jsonb,
  provenance jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, user_id),
  constraint estate_listings_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);

create unique index estate_listings_portal_external_uidx on public.estate_listings(user_id, portal, external_id) where external_id is not null;
create index estate_listings_property_idx on public.estate_listings(user_id, property_id, is_active);
create index estate_listings_url_idx on public.estate_listings(user_id, url) where url is not null;

create table public.estate_listing_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id uuid not null,
  observed_at timestamptz not null default now(),
  asking_price numeric(14,2) check (asking_price is null or asking_price > 0),
  event_type text not null default 'snapshot' check (event_type in ('snapshot','price_drop','price_increase','republished','removed','description_change','image_change')),
  payload jsonb not null default '{}'::jsonb,
  constraint estate_listing_history_listing_owner_fk foreign key (listing_id, user_id)
    references public.estate_listings(id, user_id) on delete cascade
);
create index estate_listing_history_listing_idx on public.estate_listing_history(user_id, listing_id, observed_at desc);

create table public.estate_property_images (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  source_url text,
  storage_path text,
  room_type text,
  condition_score smallint check (condition_score is null or condition_score between 0 and 100),
  analysis jsonb not null default '{}'::jsonb,
  confidence numeric(5,4) check (confidence is null or confidence between 0 and 1),
  created_at timestamptz not null default now(),
  constraint estate_property_images_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_property_images_property_idx on public.estate_property_images(user_id, property_id);

create table public.estate_market_estimates (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  estimate_type text not null check (estimate_type in ('sale','rent','arv','short_term_rent')),
  value_low numeric(14,2) check (value_low is null or value_low >= 0),
  value_mid numeric(14,2) not null check (value_mid >= 0),
  value_high numeric(14,2) check (value_high is null or value_high >= 0),
  confidence numeric(5,4) not null default 0.5 check (confidence between 0 and 1),
  method text not null default 'manual',
  source_count integer not null default 0 check (source_count >= 0),
  sources jsonb not null default '[]'::jsonb,
  model_version text not null default 'estate_market_v1',
  observed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint estate_market_estimates_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_market_estimates_property_idx on public.estate_market_estimates(user_id, property_id, estimate_type, observed_at desc);

create table public.estate_financing_scenarios (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  name text not null default 'Base',
  ltv_pct numeric(6,3) not null default 80 check (ltv_pct between 0 and 100),
  interest_pct numeric(7,4) not null default 3.25 check (interest_pct between 0 and 30),
  term_years smallint not null default 30 check (term_years between 1 and 50),
  rate_type text not null default 'fixed' check (rate_type in ('fixed','variable','mixed','cash','other')),
  origination_fees numeric(14,2) not null default 0 check (origination_fees >= 0),
  insurance_monthly numeric(14,2) not null default 0 check (insurance_monthly >= 0),
  assumptions jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint estate_financing_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_financing_property_idx on public.estate_financing_scenarios(user_id, property_id);

create table public.estate_renovation_items (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  category text not null,
  description text,
  mode text not null default 'hybrid' check (mode in ('pro','diy','hybrid')),
  pro_cost numeric(14,2) not null default 0 check (pro_cost >= 0),
  diy_material_cost numeric(14,2) not null default 0 check (diy_material_cost >= 0),
  hybrid_cost numeric(14,2) not null default 0 check (hybrid_cost >= 0),
  diy_hours numeric(10,2) not null default 0 check (diy_hours >= 0),
  difficulty smallint not null default 50 check (difficulty between 0 and 100),
  professional_required boolean not null default false,
  estimated_rent_uplift_monthly numeric(14,2) not null default 0,
  estimated_value_uplift numeric(14,2) not null default 0,
  confidence numeric(5,4) not null default 0.5 check (confidence between 0 and 1),
  created_at timestamptz not null default now(),
  constraint estate_renovation_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_renovation_property_idx on public.estate_renovation_items(user_id, property_id);

create table public.estate_deal_analyses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  strategy text not null default 'traditional_rental',
  model_version text not null default 'estate_financial_v1.0.0',
  inputs jsonb not null,
  outputs jsonb not null,
  score numeric(5,2) check (score is null or score between 0 and 100),
  score_components jsonb not null default '[]'::jsonb,
  stress_test jsonb not null default '{}'::jsonb,
  data_confidence numeric(5,4) not null default 0.5 check (data_confidence between 0 and 1),
  verdict text check (verdict is null or verdict in ('discard','monitor','analyze','visit','negotiate','go')),
  created_at timestamptz not null default now(),
  constraint estate_deal_analyses_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_deal_analyses_property_idx on public.estate_deal_analyses(user_id, property_id, created_at desc);

create table public.estate_risks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  category text not null check (category in ('financial','technical','legal','rental','market','liquidity','financing','renovation','environmental','building')),
  severity smallint not null default 50 check (severity between 0 and 100),
  confidence numeric(5,4) not null default 0.5 check (confidence between 0 and 1),
  title text not null,
  description text,
  source text,
  is_kill_switch boolean not null default false,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  constraint estate_risks_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_risks_property_idx on public.estate_risks(user_id, property_id, severity desc);

create table public.estate_audit_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid,
  event_type text not null,
  entity_type text,
  entity_id text,
  source text,
  model_version text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint estate_audit_property_owner_fk foreign key (property_id, user_id)
    references public.estate_properties(id, user_id) on delete cascade
);
create index estate_audit_user_time_idx on public.estate_audit_events(user_id, created_at desc);

-- RLS is the primary browser-access security boundary.
alter table public.estate_investor_profiles enable row level security;
alter table public.estate_properties enable row level security;
alter table public.estate_listings enable row level security;
alter table public.estate_listing_history enable row level security;
alter table public.estate_property_images enable row level security;
alter table public.estate_market_estimates enable row level security;
alter table public.estate_financing_scenarios enable row level security;
alter table public.estate_renovation_items enable row level security;
alter table public.estate_deal_analyses enable row level security;
alter table public.estate_risks enable row level security;
alter table public.estate_audit_events enable row level security;

revoke all on public.estate_investor_profiles from anon;
revoke all on public.estate_properties from anon;
revoke all on public.estate_listings from anon;
revoke all on public.estate_listing_history from anon;
revoke all on public.estate_property_images from anon;
revoke all on public.estate_market_estimates from anon;
revoke all on public.estate_financing_scenarios from anon;
revoke all on public.estate_renovation_items from anon;
revoke all on public.estate_deal_analyses from anon;
revoke all on public.estate_risks from anon;
revoke all on public.estate_audit_events from anon;

grant select, insert, update, delete on public.estate_investor_profiles to authenticated;
grant select, insert, update, delete on public.estate_properties to authenticated;
grant select, insert, update, delete on public.estate_listings to authenticated;
grant select, insert, update, delete on public.estate_listing_history to authenticated;
grant select, insert, update, delete on public.estate_property_images to authenticated;
grant select, insert, update, delete on public.estate_market_estimates to authenticated;
grant select, insert, update, delete on public.estate_financing_scenarios to authenticated;
grant select, insert, update, delete on public.estate_renovation_items to authenticated;
grant select, insert, update, delete on public.estate_deal_analyses to authenticated;
grant select, insert, update, delete on public.estate_risks to authenticated;
grant select, insert on public.estate_audit_events to authenticated;
grant usage, select on sequence public.estate_listing_history_id_seq to authenticated;
grant usage, select on sequence public.estate_audit_events_id_seq to authenticated;

-- Policies are explicit rather than relying on a generic SECURITY DEFINER helper.
create policy estate_investor_profiles_select_own on public.estate_investor_profiles for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_investor_profiles_insert_own on public.estate_investor_profiles for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_investor_profiles_update_own on public.estate_investor_profiles for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_investor_profiles_delete_own on public.estate_investor_profiles for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_properties_select_own on public.estate_properties for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_properties_insert_own on public.estate_properties for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_properties_update_own on public.estate_properties for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_properties_delete_own on public.estate_properties for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_listings_select_own on public.estate_listings for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_listings_insert_own on public.estate_listings for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_listings_update_own on public.estate_listings for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_listings_delete_own on public.estate_listings for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_listing_history_select_own on public.estate_listing_history for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_listing_history_insert_own on public.estate_listing_history for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_listing_history_update_own on public.estate_listing_history for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_listing_history_delete_own on public.estate_listing_history for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_property_images_select_own on public.estate_property_images for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_property_images_insert_own on public.estate_property_images for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_property_images_update_own on public.estate_property_images for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_property_images_delete_own on public.estate_property_images for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_market_estimates_select_own on public.estate_market_estimates for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_market_estimates_insert_own on public.estate_market_estimates for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_market_estimates_update_own on public.estate_market_estimates for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_market_estimates_delete_own on public.estate_market_estimates for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_financing_select_own on public.estate_financing_scenarios for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_financing_insert_own on public.estate_financing_scenarios for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_financing_update_own on public.estate_financing_scenarios for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_financing_delete_own on public.estate_financing_scenarios for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_renovation_select_own on public.estate_renovation_items for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_renovation_insert_own on public.estate_renovation_items for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_renovation_update_own on public.estate_renovation_items for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_renovation_delete_own on public.estate_renovation_items for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_deal_analyses_select_own on public.estate_deal_analyses for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_deal_analyses_insert_own on public.estate_deal_analyses for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_deal_analyses_update_own on public.estate_deal_analyses for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_deal_analyses_delete_own on public.estate_deal_analyses for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_risks_select_own on public.estate_risks for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_risks_insert_own on public.estate_risks for insert to authenticated with check ((select auth.uid()) = user_id);
create policy estate_risks_update_own on public.estate_risks for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy estate_risks_delete_own on public.estate_risks for delete to authenticated using ((select auth.uid()) = user_id);

create policy estate_audit_select_own on public.estate_audit_events for select to authenticated using ((select auth.uid()) = user_id);
create policy estate_audit_insert_own on public.estate_audit_events for insert to authenticated with check ((select auth.uid()) = user_id);

commit;
